/*

Given a string of length n, generate all of its subsequences.

A subsequence of a given string (sequence) is a string (sequence) that is generated by
removing zero or more characters from the given string (sequence) without changing its
order.

Example

	Input : inp[] = "abc"
	Output: ["", "c", "b", "bc", "a", "ac", "ab", "abc"]

Constraints

  1 < n < 10

*/

#include<iostream>
#include<set>

using namespace std;

set<string> s;

void f(char inp[], char out[], int i, int j) {

	// base case

	if (inp[i] == '\0') {
		out[j] = '\0';
		// cout << out << endl;

		string outStr(out);
		s.insert(outStr);

		// s.insert(string(out));

		return;
	}

	// recursive case

	// f(i, j) = take a sequence of decisions for characters in the inp[] from
	// index i to n-1 such that the next free index in the out[] is j

	// f(i, j) = generate subsequences for inp[i...n-1] such that the next free index
	// in the out[] is j

	// decide for inp[i]

	// option 1 : include inp[i] to the out[]

	out[j] = inp[i];
	f(inp, out, i + 1, j + 1);

	// option 2 : exclude inp[i] from the out[]

	f(inp, out, i + 1, j);

}

int main() {

	char inp[] = "abc";
	char out[10]; // based on constraints

	f(inp, out, 0, 0);

	for (string subseq : s) {
		cout << subseq << endl;
	}

	cout << endl;

	return 0;
}
